"""Analysis engine: parses Python files and runs all detectors.

Supports two backends:
  - "ast"  (default) — uses Python's built-in ast module, no dependencies
  - "antlr"           — uses ANTLR4 parser (requires antlr4-python3-runtime)
"""

from __future__ import annotations

import ast
import os
from pathlib import Path

from quali2.analysis.metrics import compute_metrics
from quali2.domain.models import AnalysisData, FileReport, ProjectReport, Smell
from quali2.detectors.architecture import (
    detect_architecture_smells,
    detect_cross_file_smells,
)
from quali2.detectors.design import detect_design_smells

MAX_FILE_BYTES = 200_000

SKIP_DIR_NAMES = frozenset(
    (
        "__pycache__",
        ".git",
        ".venv",
        "venv",
        "node_modules",
        ".tox",
        ".mypy_cache",
        "antlr",
    )
)

AUTO_GENERATED_MARKERS = (
    "Automatically generated by ANTLR",
    "ANTLR GENERATED CODE",
    "by ANTLR",
)


# ── Backend: AST (default) ─────────────────────────────────────────────────


def _parse_ast(file_path: str) -> tuple[AnalysisData, str, ast.AST | None]:
    """Parse using Python's ast module. Returns (data, source, tree)."""
    from quali2.analysis.ast_visitor import AstCodeVisitor

    with open(file_path, encoding="utf-8", errors="replace") as f:
        source = f.read()

    source_lines = source.splitlines()
    try:
        tree = ast.parse(source, filename=file_path)
    except SyntaxError:
        return (
            AnalysisData(file_path=file_path, total_lines=len(source_lines)),
            source,
            None,
        )

    visitor = AstCodeVisitor(file_path, source_lines)
    visitor.visit(tree)
    return visitor.data, source, tree


def _analyze_ast(data: AnalysisData, source: str, tree: ast.AST | None) -> list[Smell]:
    """Run detectors using AST backend."""
    smells: list[Smell] = []
    smells.extend(detect_architecture_smells(data))
    smells.extend(detect_design_smells(data, source))
    if tree is not None:
        smells.extend(_impl_smells_ast(data, source, tree))
        smells.extend(_ml_smells_ast(data, source, tree))
    else:
        # Fallback: line-based only
        smells.extend(_impl_smells_lines(data.file_path, source))
    return smells


def _impl_smells_ast(data: AnalysisData, source: str, tree: ast.AST) -> list[Smell]:
    from quali2.detectors.ast_detectors import (
        ast_detect_complex_conditionals,
        ast_detect_empty_catch_clauses,
        ast_detect_long_lambdas,
        ast_detect_long_message_chains,
        ast_detect_magic_numbers,
        ast_detect_missing_default,
    )
    from quali2.detectors.implementation import (
        WHITELISTED_NUMBERS,
        _check_function_smells,
        _check_line_smells,
    )

    fp = data.file_path
    lines = source.splitlines()
    all_funcs = list(data.top_level_functions)
    for cls in data.classes:
        all_funcs.extend(cls.methods)

    smells: list[Smell] = []
    smells.extend(_check_function_smells(fp, all_funcs))
    smells.extend(_check_line_smells(fp, lines))
    smells.extend(ast_detect_empty_catch_clauses(fp, tree))
    smells.extend(ast_detect_magic_numbers(fp, data, tree, source))
    smells.extend(ast_detect_complex_conditionals(fp, tree))
    smells.extend(ast_detect_missing_default(fp, tree))
    smells.extend(ast_detect_long_message_chains(fp, tree))
    smells.extend(ast_detect_long_lambdas(fp, tree))
    return smells


def _ml_smells_ast(data: AnalysisData, source: str, tree: ast.AST) -> list[Smell]:
    from quali2.detectors.ast_detectors import (
        ast_detect_ambiguous_merge_key,
        ast_detect_broken_nan,
        ast_detect_chain_indexing,
        ast_detect_forward_bypass,
        ast_detect_unnecessary_iteration,
    )
    from quali2.detectors.ml import _check_line_smells as _ml_line_smells

    uses_pandas = any(
        "pandas" in imp.module or imp.alias == "pd" for imp in data.imports
    )
    uses_numpy = any("numpy" in imp.module or imp.alias == "np" for imp in data.imports)
    uses_torch = any("torch" in imp.module for imp in data.imports)

    if not (uses_pandas or uses_numpy or uses_torch):
        return []

    fp = data.file_path
    lines = source.splitlines()
    smells: list[Smell] = []

    if uses_pandas or uses_numpy:
        smells.extend(ast_detect_broken_nan(fp, tree))
    if uses_pandas:
        smells.extend(ast_detect_chain_indexing(fp, tree))
        smells.extend(ast_detect_unnecessary_iteration(fp, tree))
        smells.extend(_ml_line_smells(fp, lines, uses_pandas=True))
    if uses_torch:
        smells.extend(ast_detect_forward_bypass(fp, tree))

    return smells


def _impl_smells_lines(fp: str, source: str) -> list[Smell]:
    """Line-only implementation smells when AST parsing fails."""
    from quali2.detectors.implementation import _check_line_smells

    return _check_line_smells(fp, source.splitlines())


# ── Backend: ANTLR ──────────────────────────────────────────────────────────


def _parse_antlr(file_path: str) -> tuple[AnalysisData, str, object | None]:
    """Parse using ANTLR4. Returns (data, source, token_stream)."""
    from antlr4 import CommonTokenStream, InputStream

    from quali2.antlr.Python3Lexer import Python3Lexer
    from quali2.antlr.Python3Parser import Python3Parser
    from quali2.analysis.visitor import PythonAnalysisVisitor

    with open(file_path, encoding="utf-8", errors="replace") as f:
        source = f.read()

    source_lines = source.splitlines()
    input_stream = InputStream(source)
    lexer = Python3Lexer(input_stream)
    token_stream = CommonTokenStream(lexer)
    parser = Python3Parser(token_stream)

    try:
        tree = parser.file_input()
    except Exception:
        return (
            AnalysisData(file_path=file_path, total_lines=len(source_lines)),
            source,
            None,
        )

    visitor = PythonAnalysisVisitor(file_path, source_lines)
    visitor.visit(tree)
    return visitor.data, source, token_stream


def _analyze_antlr(data: AnalysisData, source: str, token_stream) -> list[Smell]:
    """Run detectors using ANTLR backend."""
    from quali2.detectors.implementation import detect_implementation_smells
    from quali2.detectors.ml import detect_ml_smells

    smells: list[Smell] = []
    smells.extend(detect_architecture_smells(data))
    smells.extend(detect_design_smells(data, source))
    smells.extend(detect_implementation_smells(data, source, token_stream))
    smells.extend(detect_ml_smells(data, source, token_stream))
    return smells


# ── Public API ──────────────────────────────────────────────────────────────

_BACKENDS = {
    "ast": (_parse_ast, _analyze_ast),
    "antlr": (_parse_antlr, _analyze_antlr),
}


def parse_file(
    file_path: str,
    backend: str = "ast",
) -> tuple[AnalysisData, str, object | None]:
    """Parse a single Python file. Returns (data, source, parse_artifact)."""
    parse_fn = _BACKENDS[backend][0]
    return parse_fn(file_path)


def analyze_file(file_path: str, backend: str = "ast") -> FileReport:
    """Full analysis of one file."""
    parse_fn, analyze_fn = _BACKENDS[backend]
    data, source, artifact = parse_fn(file_path)
    metrics = compute_metrics(data)
    smells = analyze_fn(data, source, artifact)
    return FileReport(
        file_path=file_path, smells=smells, metrics=metrics, analysis=data
    )


def analyze_project(path: str, backend: str = "ast") -> ProjectReport:
    """Analyze a directory or single Python file."""
    files = _discover_files(path)
    parse_fn, analyze_fn = _BACKENDS[backend]

    reports: list[FileReport] = []
    all_data: list[AnalysisData] = []
    for f in files:
        data, source, artifact = parse_fn(f)
        metrics = compute_metrics(data)
        smells = analyze_fn(data, source, artifact)
        reports.append(
            FileReport(file_path=f, smells=smells, metrics=metrics, analysis=data)
        )
        all_data.append(data)

    if len(all_data) > 1:
        cross_smells = detect_cross_file_smells(all_data)
        report_map = {r.file_path: r for r in reports}
        for s in cross_smells:
            if s.file_path in report_map:
                report_map[s.file_path].smells.append(s)

    return ProjectReport(files=reports)


# ── File discovery ──────────────────────────────────────────────────────────


def _discover_files(path: str) -> list[str]:
    p = Path(path)
    if p.is_file() and p.suffix == ".py":
        return [str(p)]
    if p.is_dir():
        results: list[str] = []
        for root, dirs, filenames in os.walk(p):
            dirs[:] = [d for d in dirs if d not in SKIP_DIR_NAMES]
            for fn in sorted(filenames):
                if not fn.endswith(".py"):
                    continue
                fp = os.path.join(root, fn)
                if _should_skip(fp):
                    continue
                results.append(fp)
        return results
    return []


def _should_skip(file_path: str) -> bool:
    try:
        size = os.path.getsize(file_path)
    except OSError:
        return True
    if size > MAX_FILE_BYTES:
        return True
    try:
        with open(file_path, encoding="utf-8", errors="replace") as f:
            head = f.read(500)
        if any(marker in head for marker in AUTO_GENERATED_MARKERS):
            return True
    except OSError:
        return True
    return False
