"""Analysis engine: parses Python files via ANTLR4 and runs all detectors."""

from __future__ import annotations

import os
from pathlib import Path

from antlr4 import CommonTokenStream, InputStream

from quali2.antlr.Python3Lexer import Python3Lexer
from quali2.antlr.Python3Parser import Python3Parser
from quali2.analysis.metrics import compute_metrics
from quali2.analysis.visitor import PythonAnalysisVisitor
from quali2.domain.models import AnalysisData, FileReport, ProjectReport, Smell
from quali2.detectors.architecture import (
    detect_architecture_smells,
    detect_cross_file_smells,
)
from quali2.detectors.design import detect_design_smells
from quali2.detectors.implementation import detect_implementation_smells
from quali2.detectors.ml import detect_ml_smells

MAX_FILE_BYTES = 200_000

SKIP_DIR_NAMES = frozenset(
    ("__pycache__", ".git", ".venv", "venv", "node_modules", ".tox", ".mypy_cache", "antlr")
)

AUTO_GENERATED_MARKERS = (
    "Automatically generated by ANTLR",
    "ANTLR GENERATED CODE",
    # ANTLR4 Python runtime output: "# Generated from ... by ANTLR 4.x"
    "by ANTLR",
)


def parse_file(
    file_path: str,
) -> tuple[AnalysisData, str, CommonTokenStream | None]:
    """Parse a single Python file.

    Returns (analysis_data, source_text, token_stream).
    token_stream is None if parsing failed.
    """
    with open(file_path, encoding="utf-8", errors="replace") as f:
        source = f.read()

    source_lines = source.splitlines()
    input_stream = InputStream(source)
    lexer = Python3Lexer(input_stream)
    token_stream = CommonTokenStream(lexer)
    parser = Python3Parser(token_stream)

    try:
        tree = parser.file_input()
    except Exception:
        return (
            AnalysisData(file_path=file_path, total_lines=len(source_lines)),
            source,
            None,
        )

    visitor = PythonAnalysisVisitor(file_path, source_lines)
    visitor.visit(tree)
    return visitor.data, source, token_stream


def analyze_file(file_path: str) -> FileReport:
    """Full analysis of one file: parse -> metrics -> smell detection."""
    data, source, token_stream = parse_file(file_path)
    metrics = compute_metrics(data)

    smells: list[Smell] = []
    smells.extend(detect_architecture_smells(data))
    smells.extend(detect_design_smells(data, source))
    smells.extend(detect_implementation_smells(data, source, token_stream))
    smells.extend(detect_ml_smells(data, source, token_stream))

    return FileReport(
        file_path=file_path,
        smells=smells,
        metrics=metrics,
        analysis=data,
    )


def analyze_project(path: str) -> ProjectReport:
    """Analyze a directory or single Python file."""
    files = _discover_files(path)

    reports: list[FileReport] = []
    all_data: list[AnalysisData] = []
    for f in files:
        data, source, token_stream = parse_file(f)
        metrics = compute_metrics(data)
        smells: list[Smell] = []
        smells.extend(detect_architecture_smells(data))
        smells.extend(detect_design_smells(data, source))
        smells.extend(detect_implementation_smells(data, source, token_stream))
        smells.extend(detect_ml_smells(data, source, token_stream))
        reports.append(
            FileReport(file_path=f, smells=smells, metrics=metrics, analysis=data)
        )
        all_data.append(data)

    # Cross-file analysis
    if len(all_data) > 1:
        cross_smells = detect_cross_file_smells(all_data)
        report_map = {r.file_path: r for r in reports}
        for s in cross_smells:
            if s.file_path in report_map:
                report_map[s.file_path].smells.append(s)

    return ProjectReport(files=reports)


def _discover_files(path: str) -> list[str]:
    p = Path(path)
    if p.is_file() and p.suffix == ".py":
        return [str(p)]
    if p.is_dir():
        results: list[str] = []
        for root, dirs, filenames in os.walk(p):
            dirs[:] = [d for d in dirs if d not in SKIP_DIR_NAMES]
            for fn in sorted(filenames):
                if not fn.endswith(".py"):
                    continue
                fp = os.path.join(root, fn)
                if _should_skip(fp):
                    continue
                results.append(fp)
        return results
    return []


def _should_skip(file_path: str) -> bool:
    """Skip auto-generated or excessively large files."""
    try:
        size = os.path.getsize(file_path)
    except OSError:
        return True
    if size > MAX_FILE_BYTES:
        return True
    try:
        with open(file_path, encoding="utf-8", errors="replace") as f:
            head = f.read(500)
        if any(marker in head for marker in AUTO_GENERATED_MARKERS):
            return True
    except OSError:
        return True
    return False
